[package]
name = "git-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.34", features = ["derive"] }
hex = "0.4.3"
memchr = "2.7.4"
sha1 = "0.10.6"
similar = "2.7.0"

[dev-dependencies]
tempfile = "3.19.1"
